{
 "title": "FTD",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "FTD",
    "query": {
     "query": "label_values(cseSysUpTime,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Helth LED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cfprEquipmentHealthLedHealthLedState{name=\"$hostname\"}",
     "legendFormat": "{{Description}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cseSysMemoryUtilization{name=\"$hostname\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "cseSysCPUUtilization{name=\"$hostname\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Chassis",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "cfprEquipmentChassisThermal{name=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cfprEquipmentChassisPower{name=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cfprEquipmentChassisOperState{name=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cfprEquipmentChassisLicState{name=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cfprEquipmentHealthLedColor{name=\"$hostname\"}",
     "legendFormat": "{{Description}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "cfprMemoryUnitThermal{name=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cfprMemoryUnitOperState{name=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO Card",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "cfprEquipmentSwitchIOCardThermal{name=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cfprEquipmentSwitchIOCardOperState{name=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File System Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cfprSmDiskFileSystemUsedKb{name=\"$hostname\"}/cfprSmDiskFileSystemTotalKb{name=\"$hostname\"}",
     "legendFormat": "{{Description}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cseSysUpTime{name=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "cfprProcessorUnitThermal{name=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cfprProcessorUnitOperState{name=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cfprStorageLocalDiskDiskState{name=\"$hostname\"}",
     "legendFormat": "{{Description}}"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "gridPos": { "h": 26, "w": 14, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{name=\"$hostname\", ifDescr!~\"(?i).*vlan.*|Null0\"}[5m]) * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCOutOctets{name=\"$hostname\", ifDescr!~\"(?i).*vlan.*|Null0\"}[5m]) * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "ifAdminStatus{name=\"$hostname\", ifDescr!~\"(?i).*vlan.*|Null0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ifOperStatus{name=\"$hostname\", ifDescr!~\"(?i).*vlan.*|Null0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ifHighSpeed{name=\"$hostname\", ifDescr!~\"(?i).*vlan.*|Null0\"} * 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Card",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 15 },
   "targets": [
    {
     "expr": "cfprEquipmentSwitchCardPower{name=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cfprEquipmentSwitchCardOperState{name=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cfprEquipmentSwitchCardState{name=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Supply",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "cfprEquipmentPsuThermal{name=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cfprEquipmentPsuPower{name=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cfprEquipmentPsuPerf{name=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cfprEquipmentPsuOperState{name=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Module",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 25 },
   "targets": [
    {
     "expr": "cfprEquipmentFanModuleThermal{name=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cfprEquipmentFanModulePower{name=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cfprEquipmentFanModulePerf{name=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cfprEquipmentFanModuleOperState{name=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flt Aggr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 33 },
   "targets": [
    {
     "expr": "increase(cfprEquipmentSwitchIOCardFltAggr[5m])",
     "legendFormat": "{{Description}}"
    },
    {
     "expr": "increase(cfprComputeBladeFltAggr[5m])",
     "legendFormat": "{{Description}}"
    },
    {
     "expr": "increase(cfprEquipmentChassisFltAggr[5m])",
     "legendFormat": "{{Description}}"
    },
    {
     "expr": "increase(cfprEquipmentEpmFpgaFltAggr[5m])",
     "legendFormat": "{{Description}}"
    },
    {
     "expr": "increase(cfprEquipmentFanFltAggr[5m])",
     "legendFormat": "Module{{fanModule}}-{{Description}}"
    },
    {
     "expr": "increase(cfprEquipmentFanModuleFltAggr[5m])",
     "legendFormat": "{{Description}}"
    },
    {
     "expr": "increase(cfprEquipmentPsuFltAggr[5m])",
     "legendFormat": "{{Description}}"
    },
    {
     "expr": "increase(cfprEquipmentSwitchCardFltAggr[5m])",
     "legendFormat": "{{Description}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Utilization",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cseSysMemoryUtilization{name=\"$hostname\"}",
       "legendFormat": "Memory"
      },
      {
       "expr": "cseSysCPUUtilization{name=\"$hostname\"}",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cseSysMemoryUtilization{name=\"$hostname\"}",
       "legendFormat": "Memory"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cseSysCPUUtilization{name=\"$hostname\"}",
       "legendFormat": "CPU"
      }
     ]
    }
   ]
  },
  {
   "title": "File System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "File System Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "cfprSmDiskFileSystemUsedKb{name=\"$hostname\"}/cfprSmDiskFileSystemTotalKb{name=\"$hostname\"}",
       "legendFormat": "{{Description}}"
      }
     ]
    },
    {
     "title": "File System Usage",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "cfprSmDiskFileSystemUsedKb{name=\"$hostname\"}/cfprSmDiskFileSystemTotalKb{name=\"$hostname\"}",
       "legendFormat": "{{Description}}"
      },
      {
       "expr": "cfprSmDiskFileSystemUsedKb{name=\"$hostname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cfprSmDiskFileSystemFreeKb{name=\"$hostname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cfprSmDiskFileSystemTotalKb{name=\"$hostname\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cfprStorageItemOperState{name=\"$hostname\"}",
       "legendFormat": "{{Description}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "cfprProcessorUnitThermal{name=\"$hostname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cfprProcessorUnitPower{name=\"$hostname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cfprProcessorUnitPerf{name=\"$hostname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cfprProcessorUnitOperState{name=\"$hostname\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Thermal",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 65 },
     "targets": [
      {
       "expr": "cfprProcessorUnitThermal{name=\"$hostname\"}",
       "legendFormat": "{{Description}}"
      }
     ]
    },
    {
     "title": "State",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 65 },
     "targets": [
      {
       "expr": "cfprProcessorUnitOperState{name=\"$hostname\"}",
       "legendFormat": "{{Description}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "cfprMemoryUnitThermal{name=\"$hostname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cfprMemoryUnitPower{name=\"$hostname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cfprMemoryUnitPerf{name=\"$hostname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cfprMemoryUnitOperState{name=\"$hostname\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Fan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fan Module",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "cfprEquipmentFanModuleThermal{name=\"$hostname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cfprEquipmentFanModulePower{name=\"$hostname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cfprEquipmentFanModulePerf{name=\"$hostname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cfprEquipmentFanModuleOperState{name=\"$hostname\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fan",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 88 },
     "targets": [
      {
       "expr": "cfprEquipmentFanThermal{name=\"$hostname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cfprEquipmentFanPower{name=\"$hostname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cfprEquipmentFanPerf{name=\"$hostname\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "cfprEquipmentFanOperState{name=\"$hostname\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(ifHCInOctets{name=\"$hostname\"}[5m]) * 8",
       "legendFormat": "{{ifName}}_{{ifAlias}}"
      }
     ]
    },
    {
     "title": "Output rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(ifHCOutOctets{name=\"$hostname\"}[5m]) * 8",
       "legendFormat": "{{ifName}}_{{ifAlias}}"
      }
     ]
    },
    {
     "title": "Input rate [daily sum]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "increase(ifHCInOctets{name=\"$hostname\"}[24h] offset -1d)",
       "legendFormat": "{{ifName}}_{{ifAlias}}"
      }
     ]
    },
    {
     "title": "Output rate [daily sum]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "increase(ifHCOutOctets{name=\"$hostname\"}[24h] offset -1d)",
       "legendFormat": "{{ifName}}_{{ifAlias}}"
      }
     ]
    },
    {
     "title": "Input rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(ifHCInOctets{name=\"$hostname\", ifName=~\"Gi.*|Te.*|Eth.*\"}[5m]) * 8)",
       "legendFormat": "{{ifName}}_{{ifAlias}}"
      }
     ]
    },
    {
     "title": "Output rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(ifHCOutOctets{name=\"$hostname\", ifName=~\"Gi.*|Te.*|Eth.*\"}[5m]) * 8)",
       "legendFormat": "{{ifName}}_{{ifAlias}}"
      }
     ]
    },
    {
     "title": "Input Discard/Error",
     "type": "timeseries",
     "description": "packet per seconds ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(ifInDiscards{name=\"$hostname\"}[24h] offset -1d)  > 0",
       "legendFormat": "Discard__{{ifName}}_{{ifAlias}}"
      },
      {
       "expr": "increase(ifInErrors{name=\"$hostname\"}[24h] offset -1d) > 0",
       "legendFormat": "Error__{{ifName}}_{{ifAlias}}"
      }
     ]
    },
    {
     "title": "Output Discard/Error",
     "type": "timeseries",
     "description": "packet per seconds ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(ifOutDiscards{name=\"$hostname\"}[24h] offset -1d) > 0",
       "legendFormat": "Discard__{{ifName}}_{{ifAlias}}"
      },
      {
       "expr": "increase(ifOutErrors{name=\"$hostname\"}[24h] offset -1d) > 0",
       "legendFormat": "Error__{{ifName}}_{{ifAlias}}"
      }
     ]
    }
   ]
  }
 ]
}